import os
import subprocess
import sys

import requests

from . import agent  # noqa: F401 — ensures genai is configured

EXCLUDED = [
    ":(exclude)package-lock.json",
    ":(exclude)yarn.lock",
    ":(exclude)*.lock",
    ":(exclude)*.min.js",
    ":(exclude)*.min.css",
]
MAX_DIFF_CHARS = 60_000


def get_pr_diff() -> str:
    base = os.environ.get("BASE_BRANCH", "main")
    subprocess.run(["git", "fetch", "origin", base], check=True, capture_output=True)
    result = subprocess.run(
        ["git", "diff", f"origin/{base}...HEAD", "--"] + EXCLUDED,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def post_comment(body: str) -> None:
    repo = os.environ["GITHUB_REPOSITORY"]
    pr_number = os.environ["PR_NUMBER"]
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    resp = requests.post(url, json={"body": body}, headers=headers, timeout=15)
    resp.raise_for_status()


def main() -> None:
    diff = get_pr_diff()
    if not diff.strip():
        print("No meaningful diff found — skipping review.")
        sys.exit(0)

    truncated = len(diff) > MAX_DIFF_CHARS
    if truncated:
        diff = diff[:MAX_DIFF_CHARS]

    pr_title = os.environ.get("PR_TITLE", "")
    prompt = (
        f"PR Title: {pr_title}\n\n"
        f"Review this diff:\n\n```diff\n{diff}\n```"
    )
    if truncated:
        prompt += "\n\n*(diff truncated at 60,000 chars — use get_file_content for full file context)*"

    from .agent import model
    chat = model.start_chat(enable_automatic_function_calling=True)
    response = chat.send_message(prompt)

    footer = "\n\n---\n*🤖 Generated by Gemini 1.5 Flash — [AI PR Review](https://github.com/google/generative-ai-python)*"
    if truncated:
        footer = "\n\n> ⚠️ Diff was truncated. Some files may not have been reviewed." + footer

    post_comment(f"## AI Code Review\n\n{response.text}{footer}")
    print("Review posted successfully.")


if __name__ == "__main__":
    main()
