"""add assigned_reviewer_id column

Revision ID: 0bf19154c081
Revises: 54d1c5b3895d
Create Date: 2026-06-03 14:39:35.126370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf19154c081'
down_revision = '54d1c5b3895d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_reviewer_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint(batch_op.f('leaves_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_reviewer_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leaves_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('assigned_reviewer_id')

    # ### end Alembic commands ###
