"""make company name unique among active companies

Revision ID: 10279fb407bf
Revises: 876968a406a1
Create Date: 2026-03-19 10:17:26.447013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10279fb407bf'
down_revision = '876968a406a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('companies_name_key'), type_='unique')
        batch_op.create_index('uq_companies_name_active', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('uq_companies_name_active', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('companies_name_key'), ['name'])

    # ### end Alembic commands ###
