"""add partial unique index for single active owner per company

Revision ID: 12e639502299
Revises: a5d489458649
Create Date: 2026-03-19 11:20:46.381348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e639502299'
down_revision = 'a5d489458649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.create_index('uq_active_owner_per_company', ['company_id'], unique=True, postgresql_where=sa.text("role = 'owner' AND deleted_at IS NULL"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_index('uq_active_owner_per_company', postgresql_where=sa.text("role = 'owner' AND deleted_at IS NULL"))

    # ### end Alembic commands ###
