"""empty message

Revision ID: 36520b4d0a85
Revises: 90c2cc4de4fb
Create Date: 2025-09-11 22:45:35.695047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36520b4d0a85'
down_revision = '90c2cc4de4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'])

    # ### end Alembic commands ###
