"""remove company id in shift_takeover and one owner constraint in company_user

Revision ID: 472f201c1459
Revises: d0b58bfdd74b
Create Date: 2026-06-11 10:20:43.823325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472f201c1459'
down_revision = 'd0b58bfdd74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_takeovers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shift_takeovers_company_id_fkey'), type_='foreignkey')
        batch_op.drop_column('company_id')
    op.drop_index('uq_active_owner_per_company',table_name='company_users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'uq_active_owner_per_company', 
        'company_users', 
        ['company_id'], 
        unique=True, 
        postgresql_where=sa.text("role = 'owner' AND deleted_at IS NULL")
    )
    with op.batch_alter_table('shift_takeovers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(batch_op.f('shift_takeovers_company_id_fkey'), 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
