"""fix(companyUser): remove caseace on delete

Revision ID: 58fac663ebd4
Revises: a39b5318946c
Create Date: 2025-12-11 13:47:03.814739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fac663ebd4'
down_revision = 'a39b5318946c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('company_users_company_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('company_users_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('company_users_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('company_users_company_id_fkey'), 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
