"""add deleted_at into takeovers and leaves tables

Revision ID: 876968a406a1
Revises: b4c6703e3f69
Create Date: 2026-03-11 14:43:35.997626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876968a406a1'
down_revision = 'b4c6703e3f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('shift_takeovers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_takeovers', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
