"""rename Unavailability columns

Revision ID: 9af3d94961f2
Revises: b57d3c028226
Create Date: 2025-12-23 18:05:58.369781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9af3d94961f2'
down_revision = 'b57d3c028226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_company_user_unavailability'), type_='unique')
        batch_op.create_unique_constraint('uq_company_user_unavailability', ['company_id', 'user_id', 'start_at', 'end_at'])
        batch_op.drop_column('starting_time')
        batch_op.drop_column('ending_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ending_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('starting_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_company_user_unavailability', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_company_user_unavailability'), ['company_id', 'user_id', 'starting_time', 'ending_time'])
        batch_op.drop_column('end_at')
        batch_op.drop_column('start_at')

    # ### end Alembic commands ###
