"""udpate migration

Revision ID: a06c00a30707
Revises: bb16dad02c80
Create Date: 2025-12-11 14:44:03.046161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06c00a30707'
down_revision = 'bb16dad02c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('company_users_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('company_users_company_id_fkey'), 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###
