"""replace unique constraint with partial unique index (deleted_at IS NULL)

Revision ID: a5d489458649
Revises: 46bf0e5c9fc4
Create Date: 2026-03-19 10:42:42.809002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d489458649'
down_revision = '46bf0e5c9fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_company_user_unavailability'), type_='unique')
        batch_op.create_index('uq_company_user_unavailability_active', ['company_id', 'user_id', 'start_at', 'end_at'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unavailabilities', schema=None) as batch_op:
        batch_op.drop_index('uq_company_user_unavailability_active', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_company_user_unavailability'), ['company_id', 'user_id', 'start_at', 'end_at'])

    # ### end Alembic commands ###
