"""update leave schema

Revision ID: ae1f63339628
Revises: 12e639502299
Create Date: 2026-04-28 10:11:50.229365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae1f63339628'
down_revision = '12e639502299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('end_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reject_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('leaves_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('leaves_approved_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('leaves_company_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('leaves_company_id_fkey'), 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('leaves_approved_by_fkey'), 'users', ['approved_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('leaves_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('reason')
        batch_op.drop_column('end_at')
        batch_op.drop_column('start_at')

    # ### end Alembic commands ###
