"""add deleted_at to shift_assignments and remove old unique constraint

Revision ID: b37618f851a8
Revises: bbcd5b950cf6
Create Date: 2026-02-02 09:24:32.108528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37618f851a8'
down_revision = 'bbcd5b950cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_user_shift_assignments'), type_='unique')
    ## create partial unique index (active assignment only)
    op.create_index(
        'uq_shift_assignment_active',
        'shift_assignments',
        ['user_id', 'shift_id'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL')
    )

    # ### end Alembic commands ###


def downgrade():
    # drop partial unique index
    op.drop_index(
        'uq_shift_assignment_active',
        table_name='shift_assignments'
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_shift_assignments'), ['user_id', 'shift_id'])
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
