"""init

Revision ID: bb16dad02c80
Revises: 
Create Date: 2025-12-11 14:37:57.412394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb16dad02c80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shift_assignments_assigned_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('shift_assignments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('shift_takeovers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shift_takeovers_requester_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('shift_takeovers_approved_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('shift_takeovers_responder_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['responder_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['requester_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_takeovers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shift_takeovers_responder_id_fkey'), 'users', ['responder_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('shift_takeovers_approved_by_fkey'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('shift_takeovers_requester_id_fkey'), 'users', ['requester_id'], ['id'])

    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shift_assignments_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('shift_assignments_assigned_by_fkey'), 'users', ['assigned_by'], ['id'])

    # ### end Alembic commands ###
