"""modified shift model

Revision ID: dbf21eca0f03
Revises: 9af3d94961f2
Create Date: 2026-01-08 14:45:49.655035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbf21eca0f03'
down_revision = '9af3d94961f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('end_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_shift_date'))
        batch_op.drop_constraint(batch_op.f('uq_company_shift_time'), type_='unique')
        batch_op.create_index('ix_shift_end_at', ['end_at'], unique=False)
        batch_op.create_index('ix_shift_start_at', ['start_at'], unique=False)
        batch_op.drop_column('date')
        batch_op.drop_column('ending_time')
        batch_op.drop_column('starting_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ending_time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_shift_start_at')
        batch_op.drop_index('ix_shift_end_at')
        batch_op.create_unique_constraint(batch_op.f('uq_company_shift_time'), ['company_id', 'date', 'starting_time', 'ending_time'])
        batch_op.create_index(batch_op.f('ix_shift_date'), ['date'], unique=False)
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('end_at')
        batch_op.drop_column('start_at')
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
